---

#Название playbook
- name: Instal apache2
#группа на которую производится утсановка 
  hosts: prood
#Использование рут прав
  become: yes

#задания
  tasks:

#использование перменных из ansible setup
  - name: check apt or yum
    debug: var=ansible_pkg_mgr  

  - name: install apache2 yum
    yum : name=httpd state=latest
    when: ansible_pkg_mgr == "yum"

  - name: install apache2 apt
    apt : name=apache2 state=latest
    when: ansible_pkg_mgr == "apt"

  - name: Enable apache and upstart
    service: name=apache2 state=started enabled=yes

  - name : Kak print tolko debug
    debug:
      msg: hi

#запись вывода команды в переменную
  - shell: pwd
    register: result

  - debug:
      var: result 
