---

#Название playbook
- name: Instal apache2
#группа на которую производится утсановка 
  hosts: prood
#Запуск команд с судо
  become: yes

#переменные
  vars:
    web_src : ./index.html
    web_dest: /var/www/html

#задания
  tasks:

#использование перменных из ansible setup
  - name: check apt or yum
    debug: var=ansible_pkg_mgr  
  
  - block:   #====for yum====

    - name: install apache2 yum
      yum : name=httpd state=latest

    - name: Enable apache and upstart
      service: name=httpd state=started enabled=yes

    when: ansible_pkg_mgr == "yum" 
    
  - block:   #====for apt====

    - name: install apache2 apt
      apt : name=apache2 state=latest
   
    - name: Enable apache and upstart
      service: name=apache2 state=started enabled=yes
   
    when: ansible_pkg_mgr == "apt"



  - name: copy Homepage
    copy: src={{ web_src }} dest={{ web_dest }} mode=0555

  - name : Kak print tolko debug
    debug:
      msg: hi

#запись вывода команды в переменную
  - shell: pwd
    register: result

  - debug:
      var: result 

