---

#Название playbook
- name: Instal apache2
#группа на которую производится утсановка 
  hosts: prood
#Использование рут прав
  become: yes

#задания
  tasks:
  - name: install apache2
    yum: name=apache2 state=latest

  - name: Enable apache and upstart
    service: name=apache2 state=started enabled=yes

  - name: Kak print tolko debug
    debug:
      msg: hi

#запись вывода команды в переменную
  - shell: pwd
    register: result

  - debug:
      var: result 

#использование перменных из ansible setup
  - debug: var=ansible_pkg_mgr

